"""
Foreman integration surface (thruwire/foreman): deterministic records and stagnation evidence.

This module is the *adapter* half of the integration. The Foreman-side half is the operator
bundle written by `jev-harness export foreman` (preset TOML + companion responsibility class +
README). Everything here is pure standard library plus jev-harness internals: no `foreman`, no
`pydantic`, and no network unless the caller injects a live client.

Capability matrix (declared, tested, never accidental — see the change spec):

    - `category`, `severity_score`, `confidence`, `skip_llm`, `action_recommendation`
      -> Python, TypeScript, Rust
    - `assertion_slice` -> Python, TypeScript, Rust (ported by this change)
    - `recovery`        -> Python only; `null` in TS/Rust (declared divergence)

The fingerprint algorithm used by the circuit breaker is a runtime-local implementation detail
(Python uses `hashlib`, TypeScript `node:crypto`, Rust compares normalized strings): only the
equality verdict is contractual, never a hex value.

Verified against `thruwire/foreman` @ `main` (`v0.3.0`) on 2026-09-23; re-verify by 2026-10-23.
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Union

from ..client import JevClient
from ..gates import triage_test_failure
from ..perception import find_assertion_line

FOREMAN_SCHEMA_VERSION = 1
ASSERTION_SLICE_MAX_CHARS = 500
DEFAULT_WINDOW = 5
STAGNANT_EVIDENCE = "STAGNANT_EVIDENCE"

# Operator bundle (written by `jev-harness export foreman`, byte-identical in all three runtimes).
FOREMAN_PRESET_FILENAME = "quality.jev-triage.toml"
FOREMAN_COMPANION_FILENAME = "quality_jev_triage.py"
FOREMAN_README_FILENAME = "README.md"
FOREMAN_DEFAULT_OUT_DIR = "foreman-responsibilities"

# Canonical preset for `quality.jev-triage.toml`. Only keys Foreman v0.3.0 accepts (verified
# 2026-09-23): `enabled`, `always`, `routing_instructions`, `routing_threshold`, `[checks.<id>]`
# with `instructions`/`min_threshold`, `[settings]`. The header states the pair requirement: the
# TOML only configures an *installed* class, and both halves must ship together.
FOREMAN_RESPONSIBILITY_TOML = '''# quality.jev-triage.toml — jev-harness -> Foreman integration preset.
# Verified against thruwire/foreman v0.3.0 on 2026-09-23; re-verify by 2026-10-23.
#
# SHIP THE PAIR TOGETHER: this file only *configures* a responsibility implementation that must
# already be installed in the Foreman installation (quality_jev_triage.py, class
# JevTriageResponsibility). Foreman fails at startup when either half is missing — both exit 2:
#   * class installed without this central TOML:
#       ResponsibilityConfigError: installed responsibility has no central configuration: quality.jev-triage
#   * this TOML without the class:
#       ResponsibilityConfigError: configuration has no installed responsibility implementation: quality.jev-triage
#
# Activate:  foreman run --repo <repo> --job "<job>" --responsibilities-dir <this directory>
#            (or export FOREMAN_RESPONSIBILITIES_DIR=<this directory>)
# Never place this file inside a managed repository's .foreman/ directory (that is run state).

enabled = true
always = false
routing_instructions = """
Does this job involve running automated tests, compilers, or test-suite verification where a deterministic failure classification or stagnation signal would change the next supervisory action?
"""
routing_threshold = 0.50

[checks.deterministic_recovery_available]
instructions = """
Does the latest worker or verifier output show an environment-classified failure (missing dependency, unusable environment) for which a deterministic recovery exists that the next worker turn could apply without further semantic analysis?
"""
min_threshold = 0.70

[checks.assertion_failure_critical]
instructions = """
Does the latest test evidence indicate a genuine logic regression (assertion or business-logic failure) rather than an environment or configuration problem? A high probability vetoes proposing a deterministic-recovery retry.
"""
min_threshold = 0.75

[settings]
diff_timeout_seconds = 5
'''

# Operator README shipped in the bundle (byte-identical in all three runtimes).
FOREMAN_OPERATOR_README = '''# jev-harness -> Foreman operator bundle

Generated by `jev-harness export foreman`. The three files must be installed **together** in the
Foreman installation - never inside a managed repository's `.foreman/` directory (that is run state):

1. `quality.jev-triage.toml` - the central responsibility configuration (routing + checks + settings).
2. `quality_jev_triage.py`   - the companion responsibility class (`JevTriageResponsibility`).
3. `README.md`               - this file.

## Why the pair matters (verified against thruwire/foreman v0.3.0 on 2026-09-23)

A TOML only *configures* a responsibility implementation that must already be **installed** in the
Foreman environment. Foreman exits with code 2 when either half is missing:

- class installed without the central TOML:
  `ResponsibilityConfigError: installed responsibility has no central configuration: quality.jev-triage`
- this TOML without the class:
  `ResponsibilityConfigError: configuration has no installed responsibility implementation: quality.jev-triage`

## Activation

Path A - patched launcher (works today): make the class importable in the Foreman environment and
pass it explicitly, e.g.

    responsibilities = configured_registry(config, config_dir="<this directory>",
                                           additional=[JevTriageResponsibility()])

or register the class in Foreman's `builtin_registry`, then run:

    foreman run --repo <repo> --job "<job>" --responsibilities-dir <this directory>

(`FOREMAN_RESPONSIBILITIES_DIR=<this directory>` works as an environment override.)

Path B - upstream registration: the integration PR adds a registration path so stock
`foreman run` loads the class without a patch (change `foreman-integration`, design Decision 5).

## What the class does

- Reads the latest worker output and a bounded `git diff` (timeout `diff_timeout_seconds`) once per
  assessment, keyed by `(run_id, iteration)`; re-evaluating an assessment never changes the verdict.
- Proposes `RETRY_WORKER` only when its own Jev checks clear their thresholds and the evidence
  window holds `window` assessments: a deterministic environment recovery, or a stagnation verdict
  (output **and** diff unchanged across the window). A genuine logic regression
  (`assertion_failure_critical`) vetoes the environment-recovery retry; a provably stagnant worker
  is retried regardless.
- Its `reason` is audit evidence (visible in `foreman inspect`); Foreman builds the worker steering
  text from check probabilities, so the reason does not instruct the worker.
- It never touches the network by default and never raises into the factory loop.

## Requirements

- `pip install jev-harness` inside the Foreman environment.
- Python 3.9+ (Foreman itself requires 3.11+).

Re-verify the upstream facts after 2026-10-23.
'''

# Volatile tokens stripped before fingerprinting an output tail. A worker that only re-prints
# new timestamps or durations has not made progress; a worker that changed its message has.
_VOLATILE_PATTERNS = (
    re.compile(r"\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?\b"),  # timestamps
    re.compile(r"\b\d+(?:\.\d+)?\s?(?:ms|s|sec|secs|seconds|min|mins|h|hours)\b"),  # durations
    re.compile(r"(?::\d+){1,2}(?=[\s:)\]}]|$)"),  # line references (file.py:12:5)
    re.compile(r"\bline \d+\b", re.IGNORECASE),
    re.compile(r"(?:/tmp|/var/folders/)[^\s]*"),  # temporary paths
    re.compile(r"\b[0-9a-f]{7,64}\b", re.IGNORECASE),  # commit/hash-like tokens
)
_WHITESPACE = re.compile(r"\s+")


def _normalize_output(text: str) -> str:
    """Whitespace-collapsed text with volatile tokens removed (the stagnation comparison unit)."""
    normalized = text or ""
    for pattern in _VOLATILE_PATTERNS:
        normalized = pattern.sub("<v>", normalized)
    return _WHITESPACE.sub(" ", normalized).strip()


def _fingerprint(text: str) -> str:
    """Runtime-local digest; only equality between two fingerprints is ever meaningful."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _empty_verdict(evidence: Dict[str, Any]) -> Dict[str, Any]:
    return {"should_abort": False, "reason": "", "evidence": evidence}


class ForemanTriageObserver:
    """Enriches Foreman observations with deterministic failure triage.

    One triage call classifies a *log*, not individual failures: the record list therefore holds
    exactly one entry (or none), and is shaped for `FactoryObservation.test_results`.
    """

    @staticmethod
    def extract_test_results(
        stdout: str,
        stderr: str = "",
        repo_root: Optional[Union[str, Path]] = None,
        client: Optional[JevClient] = None,
    ) -> List[Dict[str, Any]]:
        output = f"{stdout}\n{stderr}".strip()
        if not output:
            return []

        result = triage_test_failure(
            output,
            client=client or JevClient(force_mock=True),
            repo_root=Path(repo_root) if repo_root is not None else None,
        )
        if result.category == "no_failure":
            return []

        assertion_line = find_assertion_line(output) or ""
        return [
            {
                "category": result.category,
                "severity_score": result.severity_score,
                "confidence": result.confidence,
                "skip_llm": result.skip_llm,
                "action_recommendation": result.action_recommendation,
                "assertion_slice": assertion_line[:ASSERTION_SLICE_MAX_CHARS],
                "recovery": result.recovery,  # Python-only: `null` in TS/Rust (capability matrix)
                "is_mock": result.is_mock,
                "degraded_reason": result.degraded_reason,
                "foreman_schema_version": FOREMAN_SCHEMA_VERSION,
            }
        ]


class ForemanCircuitBreaker:
    """Deterministic stagnation evidence for Foreman's worker-health policy.

    Foreman exposes no structured command history, so the signals are the ones its evidence model
    actually produces: a normalized output fingerprint and a diff fingerprint. Aborting requires
    **both** to be unchanged across the whole window — a conservative AND that keeps legitimate
    fix-and-retry cycles (same tests, changing diff) from being flagged. When no snapshot carries
    a diff the breaker declines to judge instead of aborting on a single signal.

    The verdict is advisory evidence for `FactoryPolicy`; jev-harness never decides to stop a
    worker. The fingerprint algorithm is runtime-local: only equality is contractual.
    """

    @staticmethod
    def evaluate_worker_health(
        snapshots: Sequence[Mapping[str, Any]],
        window: int = DEFAULT_WINDOW,
    ) -> Dict[str, Any]:
        samples = list(snapshots or [])
        effective_window = max(2, int(window))

        if len(samples) < effective_window:
            return _empty_verdict(
                {
                    "insufficient_history": True,
                    "complete_signals": False,
                    "samples": len(samples),
                    "window": effective_window,
                    "stagnant_output": False,
                    "stagnant_diff": False,
                }
            )

        recent = samples[-effective_window:]
        diffs = [sample.get("diff") for sample in recent]
        complete_signals = all(isinstance(diff, str) for diff in diffs)

        output_fingerprints = {
            _fingerprint(_normalize_output(str(sample.get("output") or ""))) for sample in recent
        }
        stagnant_output = len(output_fingerprints) == 1

        stagnant_diff = False
        if complete_signals:
            diff_fingerprints = {_fingerprint(str(diff)) for diff in diffs}
            stagnant_diff = len(diff_fingerprints) == 1

        should_abort = bool(stagnant_output and stagnant_diff)
        return {
            "should_abort": should_abort,
            "reason": STAGNANT_EVIDENCE if should_abort else "",
            "evidence": {
                "insufficient_history": False,
                "complete_signals": complete_signals,
                "samples": len(recent),
                "window": effective_window,
                "stagnant_output": stagnant_output,
                "stagnant_diff": stagnant_diff,
            },
        }
