import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { COMMANDCODE_API_URL, JevClient, OPENCODE_API_URL } from "./client.js";
import {
  modulateReasoningEffort,
  routeModelTier,
  shouldAbortTrajectory,
  shouldNudgeContinuation,
  triageTestFailure,
  verifyStepCompletion,
} from "./gates.js";
import { runMcpServer } from "./mcp.js";

// Heuristic savings model (documented planning assumptions, NOT measured token counts):
// mirrors the Python and Rust runtimes so every metrics surface stays honest.
const ASSUMED_TOKENS_PER_TRIAGE_SKIP = 26200;
const ASSUMED_COST_PER_TRIAGE_SKIP_USD = 0.31;
const ASSUMED_TOKENS_PER_ABORT = 80000;
const ASSUMED_COST_PER_ABORT_USD = 1.2;

const ENV_EXAMPLE = `# Jev Harness provider credentials. Offline mode needs NO key (zero network calls).
# Docs: https://github.com/ismaelsoilet/jev-harness/blob/main/docs/AGENT_INTEGRATION_GUIDE.md
#
# OpenCode Zen (free tier) - https://opencode.ai/auth
# JEV_PROVIDER=opencode
# OPENCODE_API_KEY="your_key_here"
#
# TypeSafe AI (direct) - https://console.typesafe.ai
# TYPESAFE_API_KEY="your_key_here"
#
# Command Code - https://commandcode.ai/signup  (or run: cmd login)
# CMD_API_KEY="your_key_here"
#
# OpenRouter (alpha access only)
# OPENROUTER_API_KEY="your_key_here"
#
# Vercel AI Gateway
# AI_GATEWAY_API_KEY="your_key_here"
`;

async function readStdin(): Promise<string> {
  // Streaming-safe stdin read: `fs.readFileSync(0)` throws EAGAIN when the writer
  // (a live test runner) has not finished flushing the pipe.
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) {
    chunks.push(typeof chunk === "string" ? Buffer.from(chunk) : (chunk as Buffer));
  }
  return Buffer.concat(chunks).toString("utf-8");
}

async function readInput(valOrPath?: string, allowStdin: boolean = true): Promise<string> {
  if (valOrPath) {
    if (fs.existsSync(valOrPath) && fs.statSync(valOrPath).isFile()) {
      return fs.readFileSync(valOrPath, "utf-8");
    }
    return valOrPath;
  }
  if (allowStdin && !process.stdin.isTTY) {
    return await readStdin();
  }
  return "";
}

/**
 * Best-effort detection of the repository test command for the generated git hook.
 * Mirrors the Python and Rust runtimes.
 */
/**
 * Returns the project venv binary (e.g. ./.venv/bin/python) when present, else the fallback.
 * Hook-safe: paths are relative to the repository root, which is the CWD Git uses for hooks.
 */
function projectBin(cwd: string, name: string, fallback: string): string {
  const candidates = [
    path.join(".venv", "bin", name),
    path.join("venv", "bin", name),
    path.join(".venv", "Scripts", `${name}.exe`),
    path.join("venv", "Scripts", `${name}.exe`),
  ];
  for (const rel of candidates) {
    if (fs.existsSync(path.join(cwd, rel))) return `./${rel.split(path.sep).join("/")}`;
  }
  return fallback;
}

function detectTestCommand(cwd: string, override: string = ""): string {
  if (override.trim()) return override.trim();
  const pythonBin = projectBin(cwd, "python", "python3");
  const packageJson = path.join(cwd, "package.json");
  if (fs.existsSync(packageJson)) {
    try {
      const scripts = JSON.parse(fs.readFileSync(packageJson, "utf-8")).scripts || {};
      if (scripts.test) return "npm test --silent";
    } catch {
      // ignore malformed package.json
    }
  }
  if (fs.existsSync(path.join(cwd, "Cargo.toml"))) return "cargo test --quiet";
  const pyproject = path.join(cwd, "pyproject.toml");
  const pytestMarker =
    fs.existsSync(path.join(cwd, "pytest.ini")) ||
    fs.existsSync(path.join(cwd, "tox.ini")) ||
    (fs.existsSync(pyproject) && fs.readFileSync(pyproject, "utf-8").includes("[tool.pytest"));
  if (pytestMarker) return `${pythonBin} -m pytest -q`;
  if (fs.existsSync(pyproject) || fs.existsSync(path.join(cwd, "setup.py")) || fs.existsSync(path.join(cwd, "tests"))) {
    return `${pythonBin} -m unittest`;
  }
  return "";
}

/** Generated pre-commit hook: the runner decides, Jev only advises. */
function buildGitHook(testCmd: string, jevBin: string = "jev-harness"): string {
  return `#!/bin/sh
# Jev Harness pre-commit gate (generated by \`jev-harness init --git\`).
# The test runner decides whether the commit is blocked; Jev only triages a failing
# run so it can be fixed deterministically when possible.
# Regenerate with: jev-harness init --git

TEST_CMD="${testCmd}"
JEV_BIN="${jevBin}"

if [ -z "$TEST_CMD" ]; then
  echo "[jev] No test command detected. Edit this hook and set TEST_CMD (e.g. npm test)." >&2
  exit 0
fi

if ! TEST_OUTPUT=$(sh -c "$TEST_CMD" 2>&1); then
  printf '%s\n' "$TEST_OUTPUT" | "$JEV_BIN" test-gate
  exit 1
fi
exit 0
`;
}

function getPackageVersion(): string {
  try {
    const pkgPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../package.json");
    if (fs.existsSync(pkgPath)) {
      const data = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
      if (data.version) return data.version;
    }
  } catch {
    // fallback
  }
  return "0.1.14";
}

export async function runCli(argv: string[] = process.argv.slice(2)): Promise<number> {
  const args = argv;
  const isMock = args.includes("--mock");
  const isJson = args.includes("--json");

  let providerVal: string | undefined;
  const providerEq = args.find((a) => a.startsWith("--provider="));
  if (providerEq) {
    providerVal = providerEq.split("=")[1];
  } else {
    const pIdx = args.findIndex((a) => a === "--provider");
    if (pIdx !== -1) {
      providerVal = args[pIdx + 1];
    }
  }

  // Filter out flags and their argument values to find the subcommand
  const nonCommandIndices = new Set<number>();
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith("-")) {
      nonCommandIndices.add(i);
      if (
        (args[i] === "--provider" ||
          args[i] === "--log" ||
          args[i] === "-l" ||
          args[i] === "--sample" ||
          args[i] === "--plan" ||
          args[i] === "-p" ||
          args[i] === "--history" ||
          args[i] === "-H" ||
          args[i] === "--task" ||
          args[i] === "-t" ||
          args[i] === "--transcript" ||
          args[i] === "--previous-nudge" ||
          args[i] === "-P" ||
          args[i] === "--threshold" ||
          args[i] === "--criteria" ||
          args[i] === "-c" ||
          args[i] === "--output" ||
          args[i] === "-o" ||
          args[i] === "--context" ||
          args[i] === "-C" ||
          args[i] === "--target-provider" ||
          args[i] === "--model" ||
          args[i] === "-m" ||
          args[i] === "--session-context-tokens" ||
          args[i] === "--tokens" ||
          args[i] === "--supported-efforts" ||
          args[i] === "--max-lease-steps") &&
        i + 1 < args.length &&
        !args[i + 1].startsWith("-")
      ) {
        nonCommandIndices.add(i + 1);
        i++;
      }
    }
  }
  const command = args.find((_, idx) => !nonCommandIndices.has(idx));

  const client = new JevClient({ forceMock: isMock });
  if (providerVal) {
    client.provider = providerVal;
    if (providerVal === "commandcode") {
      client.baseUrl = COMMANDCODE_API_URL;
      client.model = "typesafe/jev";
    } else if (providerVal === "opencode") {
      client.baseUrl = OPENCODE_API_URL;
      client.model = "jev-1.13-free";
    }
  }

  if (args.includes("--version") || args.includes("-v") || args.includes("-V")) {
    console.log(`@ismaelsoilet/jev-harness ${getPackageVersion()}`);
    return 0;
  }

  if (command === "help" || args.includes("-h") || args.includes("--help")) {
    console.log(`
Usage: jev-harness <command> [options]

Commands:
  status                                 Show API status & engine mode
  init                                   Initialize Jev Harness config & adapters in current repo
  metrics                                Display ROI, token savings & session telemetry
  test-gate --log <file_or_string>       Triage test traceback & gate LLM calls
  abort-check --plan <text>              Guard against doom loops and unviable refactors
  route --task <text>                    Select minimal sufficient model tier
  verify --criteria <c> --output <o>     Calibrate criteria verification
  reasoning-effort --context <text>      Dynamically modulate reasoning effort per-generation (Astra-Jev)
  nudge-gate --transcript <text>         Evaluate premature stops via Jev Nudge Gate
  mcp                                    Run stdio MCP server for Cursor, Claude Desktop, Antigravity IDE

Options:
  --mock                                 Force offline heuristic simulation
  --json                                 Output machine-readable JSON
  --provider <typesafe|commandcode|...>  Override backend provider
  --target-provider <openai|deepseek|..> Target provider for reasoning effort
  --model <name>                         Target model name
  --session-context-tokens <num>         Active prompt tokens in session
  --supported-efforts <list>             Comma-separated allowed effort levels (e.g. low,medium,high)
  --max-lease-steps <num>                Maximum generation stability lease steps (default: 10)
`);
    return 0;
  }

  if (!command) {
    console.error("Error: Missing required command.");
    console.error("Run 'jev-harness --help' for usage information.");
    return 2;
  }

  if (command === "mcp") {
    await runMcpServer(client);
    return 0;
  }

  if (command === "init") {
    const cwd = process.cwd();
    console.log(`Initializing Jev Harness integration in: ${cwd}`);

    const skillsDir = path.join(cwd, ".agents", "skills", "jev-harness");
    fs.mkdirSync(skillsDir, { recursive: true });
    const skillFile = path.join(skillsDir, "SKILL.md");
    const skillContent = `---
name: jev-harness
description: Repository adapter for Jev System One.
license: MIT
---

# Local Jev Harness Adapter

This repository is connected to the global **Jev System One Harness**.
`;
    if (fs.existsSync(skillFile)) {

      console.log(`  [=] Existing agent skill preserved: ${path.relative(cwd, skillFile)}`);

    } else {

      fs.writeFileSync(skillFile, skillContent, "utf-8");

      console.log(`  [+] Created agent skill: ${path.relative(cwd, skillFile)}`);

    }

    const jevJson = path.join(cwd, ".jev.json");
    if (!fs.existsSync(jevJson)) {
      fs.writeFileSync(
        jevJson,
        JSON.stringify(
          {
            api_key: "",
            model: "jev-latest",
            skip_llm_threshold: 0.65,
            abort_threshold: 0.7,
          },
          null,
          2
        ) + "\n",
        "utf-8"
      );
      console.log(`  [+] Created repo config: ${path.relative(cwd, jevJson)}`);
    }

    const envExample = path.join(cwd, ".env.jev.example");
    if (!fs.existsSync(envExample)) {
      fs.writeFileSync(envExample, ENV_EXAMPLE, "utf-8");
      console.log(`  [+] Created env template: ${path.relative(cwd, envExample)}`);
    }

    let gitGateActive = true;
    if (args.includes("--git") || args.includes("--all")) {
      const gitHooks = path.join(cwd, ".git", "hooks");
      if (fs.existsSync(gitHooks)) {
        const marker = "Jev Harness pre-commit gate";
        const preCommit = path.join(gitHooks, "pre-commit");
        const testCmdIdx = args.indexOf("--test-cmd");
        const testCmdOverride = testCmdIdx !== -1 ? args[testCmdIdx + 1] || "" : "";
        const hookScript = buildGitHook(
          detectTestCommand(cwd, testCmdOverride),
          projectBin(cwd, "jev-harness", "jev-harness")
        );
        const existing = fs.existsSync(preCommit) ? fs.readFileSync(preCommit, "utf-8") : "";
        if (existing && !existing.toLowerCase().includes(marker.toLowerCase())) {
          const sample = path.join(gitHooks, "pre-commit.jev");
          fs.writeFileSync(sample, hookScript, "utf-8");
          fs.chmodSync(sample, 0o755);
          gitGateActive = false;
          console.log(`  [!] An existing pre-commit hook was preserved; the Jev gate is NOT active yet. Merge ${path.relative(cwd, sample)} into it (or use the pre-commit framework) to enable it.`);
        } else {
          fs.writeFileSync(preCommit, hookScript, "utf-8");
          fs.chmodSync(preCommit, 0o755);
          const detected = detectTestCommand(cwd, testCmdOverride);
          const detail = detected ? ` (test command: ${detected})` : " (no test command detected yet)";
          console.log(`  [+] Installed Git pre-commit guardrail: ${path.relative(cwd, preCommit)}${detail}`);
        }
      }
    }

    const hasCursorFlag = args.includes("--cursor") || args.includes("--all") || fs.existsSync(path.join(cwd, ".cursor"));
    if (hasCursorFlag) {
      const cursorDir = path.join(cwd, ".cursor");
      fs.mkdirSync(cursorDir, { recursive: true });
      const cursorMcp = path.join(cursorDir, "mcp.json");
      if (!fs.existsSync(cursorMcp)) {
        fs.writeFileSync(
          cursorMcp,
          JSON.stringify(
            {
              mcpServers: {
                "jev-harness": {
                  command: "npx",
                  args: ["-y", "@ismaelsoilet/jev-harness", "mcp"],
                },
              },
            },
            null,
            2
          ) + "\n",
          "utf-8"
        );
        console.log(`  [+] Created Cursor MCP config: ${path.relative(cwd, cursorMcp)}`);
      }
    }

    if (gitGateActive) {
      console.log("\n[OK] Repository configured successfully! You can now run 'jev-harness status'.\n");
    } else {
      console.log(
        "\n[!] Repository configured, but the Jev commit gate is NOT active (an existing hook was preserved). Merge .git/hooks/pre-commit.jev to enable it.\n"
      );
    }
    return 0;
  }

  if (command === "metrics") {
    const home = process.env.HOME || process.env.USERPROFILE || ".";
    const sessionPath = path.join(home, ".config", "jev", "session.json");

    if (args.includes("--reset")) {
      if (fs.existsSync(sessionPath)) {
        try {
          fs.unlinkSync(sessionPath);
        } catch {}
      }
      console.log("\n[OK] Jev Harness metrics reset successfully.\n");
      return 0;
    }

    let triageCalls = 0;
    let skippedLlm = 0;
    let abortGuards = 0;
    let deterministicRoutes = 0;
    let effortModulations = 0;
    let nudgeContinuations = 0;
    let tokensSaved = 0;
    let costSaved = 0.0;

    if (fs.existsSync(sessionPath)) {
      try {
        const val = JSON.parse(fs.readFileSync(sessionPath, "utf-8"));
        triageCalls = val.total_triage_calls || 0;
        skippedLlm = val.skipped_llm_calls || 0;
        abortGuards = val.abort_guards_triggered || 0;
        deterministicRoutes = val.deterministic_routes || 0;
        effortModulations = val.effort_modulations || 0;
        nudgeContinuations = val.nudge_continuations || 0;
        tokensSaved = val.estimated_tokens_saved || 0;
        costSaved = val.estimated_cost_saved_usd || 0.0;
      } catch {}
    }

    if (isJson) {
      console.log(
        JSON.stringify(
          {
            total_triage_calls: triageCalls,
            skipped_llm_calls: skippedLlm,
            abort_guards_triggered: abortGuards,
            deterministic_routes: deterministicRoutes,
            effort_modulations: effortModulations,
            nudge_continuations: nudgeContinuations,
            estimated_tokens_saved: tokensSaved,
            estimated_cost_saved_usd: Math.round(costSaved * 100) / 100,
            estimates_are_heuristic: true,
          },
          null,
          2
        )
      );
    } else {
      console.log("\n=== JEV HARNESS ROI & TOKEN METRICS (TS) ===");
      console.log(`Total Test Triages:      ${triageCalls}`);
      console.log(`LLM Calls Intercepted:   ${skippedLlm} (Fixed deterministically)`);
      console.log(`Doom Loops Aborted:      ${abortGuards}`);
      console.log(`Deterministic Routes:    ${deterministicRoutes}`);
      console.log(`Effort Modulations:      ${effortModulations} (Astra-Jev per-generation)`);
      console.log(`Continuation Nudges:     ${nudgeContinuations} (Jev Nudge Gate)`);
      console.log(`Estimated Tokens Saved:  ⚡ ${tokensSaved.toLocaleString()} tokens (heuristic estimate)`);
      console.log(`Estimated API Cost Saved: 💸 $${costSaved.toFixed(2)} USD (heuristic estimate)`);
      console.log(
        `Assumption Model:        ${ASSUMED_TOKENS_PER_TRIAGE_SKIP.toLocaleString()} tokens/$${ASSUMED_COST_PER_TRIAGE_SKIP_USD.toFixed(2)} per intercepted triage; ` +
          `${ASSUMED_TOKENS_PER_ABORT.toLocaleString()} tokens/$${ASSUMED_COST_PER_ABORT_USD.toFixed(2)} per aborted doom loop`
      );
      console.log("===========================================\n");
    }
    return 0;
  }

  if (command === "status") {
    console.log("\n=== JEV HARNESS (TS) STATUS ===");
    if (client.isLive) {
      if (client.provider === "opencode") {
        console.log("Provider:    OPENCODE ZEN (Free Tier)");
        console.log(`Endpoint:    ${client.baseUrl}`);
        console.log("Engine Mode: LIVE (OpenCode Zen Free Community Model)");
      } else if (client.provider === "commandcode") {
        const masked = client.apiKey && client.apiKey.length > 10 ? client.apiKey.slice(0, 6) + "..." + client.apiKey.slice(-4) : "***";
        console.log(`API Key:     Configured (${masked})`);
        console.log("Provider:    COMMAND CODE (Free $0.00/M Deal - typesafe/jev)");
        console.log(`Endpoint:    ${client.baseUrl}`);
        console.log("Engine Mode: LIVE");
      } else {
        const masked = client.apiKey && client.apiKey.length > 10 ? client.apiKey.slice(0, 6) + "..." + client.apiKey.slice(-4) : "***";
        console.log(`API Key:     Configured (${masked})`);
        console.log(`Provider:    ${client.provider.toUpperCase()}`);
        console.log(`Endpoint:    ${client.baseUrl}`);
        console.log("Engine Mode: LIVE");
      }
    } else {
      console.log("API Key:     NOT DETECTED");
      console.log("Engine Mode: SIMULATION / MOCK (Heuristic offline mode active)");
    }
    console.log(`Model:       ${client.model}`);
    console.log("===============================\n");
    return 0;
  }

  if (command === "test-gate" || command === "triage") {
    const logIdx = args.findIndex((a) => a === "--log" || a === "-l" || a === "--sample");
    let logVal = logIdx !== -1 ? args[logIdx + 1] : undefined;
    if (logIdx !== -1 && (args[logIdx] === "--log" || args[logIdx] === "-l") && logVal && !fs.existsSync(logVal)) {
      // `--log` is documented as a file: a typo must not be triaged as if it were the log text.
      console.error(`Error: log file not found: ${logVal}`);
      console.error("Hint: pass the log text as a positional argument, use --sample for a literal string, or pipe it via stdin.");
      return 2;
    }
    if (!logVal) {
      // Check for positional argument after command
      const cmdIdx = args.indexOf(command);
      if (cmdIdx !== -1 && args[cmdIdx + 1] && !args[cmdIdx + 1].startsWith("-")) {
        logVal = args[cmdIdx + 1];
      }
    }
    const text = (await readInput(logVal)).trim();

    if (!text) {
      console.error("Error: No test failure log provided. Pass --log <file_or_string> or pipe via stdin.");
      return 2;
    }

    const res = await triageTestFailure(text, client);

    if (isJson) {
      console.log(
        JSON.stringify(
          {
            category: res.category,
            confidence: res.confidence,
            skip_llm: res.skipLlm,
            skipLlm: res.skipLlm,
            skip_llm_prob: res.skipLlmProb,
            skipLlmProb: res.skipLlmProb,
            severity_score: res.severityScore,
            recommendation: res.actionRecommendation,
            action_recommendation: res.actionRecommendation,
            actionRecommendation: res.actionRecommendation,
            is_mock: res.isMock,
            isMock: res.isMock,
          },
          null,
          2
        )
      );
    } else {
      console.log("\n--- JEV TEST TRIAGE VERDICT (TS) ---");
      console.log(`Category:        ${res.category.toUpperCase()}`);
      if (res.category === "no_failure") {
        console.log("No failure detected: the test run appears successful. Nothing to triage.");
        console.log("Mode:            [DETERMINISTIC]");
        console.log("------------------------------------\n");
        return 0;
      }
      console.log(`Confidence:      ${(res.confidence * 100).toFixed(1)}%`);
      console.log(`Skip LLM Call:   ${res.skipLlm ? "YES (Save Tokens!)" : "NO (Dispatch to System 2)"}`);
      console.log(`Severity Score:  ${res.severityScore.toFixed(1)} / 4.0`);
      console.log(`Recommendation:  ${res.actionRecommendation}`);
      if (res.isMock) console.log("Mode:            [SIMULATION/MOCK]");
      console.log("------------------------------------\n");
    }
    return res.skipLlm ? 0 : 1;
  }

  if (command === "abort-check" || command === "abort") {
    const planIdx = args.findIndex((a) => a === "--plan" || a === "-p");
    const histIdx = args.findIndex((a) => a === "--history" || a === "-H");
    let plan = planIdx !== -1 ? args[planIdx + 1] : undefined;
    if (!plan) {
      const cmdIdx = args.indexOf(command);
      if (cmdIdx !== -1 && args[cmdIdx + 1] && !args[cmdIdx + 1].startsWith("-")) {
        plan = args[cmdIdx + 1];
      }
    }
    const history = histIdx !== -1 ? await readInput(args[histIdx + 1], false) : "";
    const cleanPlan = (await readInput(plan, true)).trim();

    if (!cleanPlan) {
      console.error("Error: No proposed step or plan provided. Pass --plan <text> or positional argument.");
      return 2;
    }

    const res = await shouldAbortTrajectory(cleanPlan, history, client);

    if (isJson) {
      console.log(
        JSON.stringify(
          {
            should_abort: res.shouldAbort,
            shouldAbort: res.shouldAbort,
            abort_probability: res.abortProbability,
            abortProbability: res.abortProbability,
            action: res.action,
            viability_score: res.viabilityScore,
            viabilityScore: res.viabilityScore,
            reasoning_summary: res.reasoningSummary,
            reasoningSummary: res.reasoningSummary,
            summary: res.reasoningSummary,
            is_mock: res.isMock,
            isMock: res.isMock,
          },
          null,
          2
        )
      );
    } else {
      console.log("\n--- JEV ABORT GATE VERDICT (TS) ---");
      console.log(`Should Abort:     ${res.shouldAbort ? "YES - STOP & RECONSIDER" : "NO - PROCEED"}`);
      console.log(`Abort Probability: ${(res.abortProbability * 100).toFixed(1)}%`);
      console.log(`Viability Score:   ${res.viabilityScore.toFixed(1)} / 4.0`);
      console.log(`Summary:           ${res.reasoningSummary}`);
      if (res.isMock) console.log("Mode:              [SIMULATION/MOCK]");
      console.log("-----------------------------------\n");
    }
    return res.shouldAbort ? 1 : 0;
  }

  if (command === "route") {
    const taskIdx = args.findIndex((a) => a === "--task" || a === "-t");
    let task = taskIdx !== -1 ? args[taskIdx + 1] : undefined;
    if (!task) {
      const cmdIdx = args.indexOf(command);
      if (cmdIdx !== -1 && args[cmdIdx + 1] && !args[cmdIdx + 1].startsWith("-")) {
        task = args[cmdIdx + 1];
      }
    }
    const cleanTask = (await readInput(task, true)).trim();

    if (!cleanTask) {
      console.error("Error: No task description provided. Pass --task <text> or pipe via stdin.");
      return 2;
    }

    const res = await routeModelTier(cleanTask, client);

    if (isJson) {
      console.log(
        JSON.stringify(
          {
            selected_tier: res.selectedTier,
            selectedTier: res.selectedTier,
            confidence: res.confidence,
            complexity_score: res.complexityScore,
            complexityScore: res.complexityScore,
            recommended_model: res.recommendedModel,
            recommendedModel: res.recommendedModel,
            rationale: res.rationale,
            is_mock: res.isMock,
            isMock: res.isMock,
          },
          null,
          2
        )
      );
    } else {
      console.log("\n--- JEV MODEL ROUTE VERDICT (TS) ---");
      console.log(`Selected Tier:     ${res.selectedTier.toUpperCase()}`);
      console.log(`Confidence:        ${(res.confidence * 100).toFixed(1)}%`);
      console.log(`Recommended Model: ${res.recommendedModel}`);
      console.log(`Rationale:         ${res.rationale}`);
      if (res.isMock) console.log("Mode:              [SIMULATION/MOCK]");
      console.log("------------------------------------\n");
    }
    return 0;
  }

  if (command === "verify") {
    const critIdx = args.findIndex((a) => a === "--criteria" || a === "-c");
    const outIdx = args.findIndex((a) => a === "--output" || a === "-o");
    const criteria = critIdx !== -1 ? args[critIdx + 1] : undefined;
    const output = outIdx !== -1 ? args[outIdx + 1] : undefined;
    const cleanCrit = (criteria ? await readInput(criteria, false) : "").trim();
    const cleanOut = (output ? await readInput(output, false) : "").trim();

    if (!cleanCrit || !cleanOut) {
      console.error("Error: Both --criteria and --output must be provided.");
      return 2;
    }

    const res = await verifyStepCompletion(cleanCrit, cleanOut, client);

    if (isJson) {
      console.log(
        JSON.stringify(
          {
            is_verified: res.isVerified,
            isVerified: res.isVerified,
            satisfaction_probability: res.satisfactionProbability,
            satisfactionProbability: res.satisfactionProbability,
            rigor_score: res.rigorScore,
            rigorScore: res.rigorScore,
            confidence: res.confidence,
            needs_rework: res.needsRework,
            needsRework: res.needsRework,
            is_mock: res.isMock,
            isMock: res.isMock,
          },
          null,
          2
        )
      );
    } else {
      console.log("\n--- JEV VERIFICATION VERDICT (TS) ---");
      console.log(`Verified:          ${res.isVerified ? "PASS" : "REWORK NEEDED"}`);
      console.log(`Satisfaction Prob: ${(res.satisfactionProbability * 100).toFixed(1)}%`);
      console.log(`Rigor Score:       ${res.rigorScore.toFixed(1)} / 4.0`);
      if (res.isMock) console.log("Mode:              [SIMULATION/MOCK]");
      console.log("-------------------------------------\n");
    }
    return res.isVerified ? 0 : 1;
  }

  if (command === "reasoning-effort" || command === "astra-jev" || command === "effort") {
    const ctxIdx = args.findIndex((a) => a === "--context" || a === "-C");
    let ctx = ctxIdx !== -1 ? args[ctxIdx + 1] : undefined;
    if (!ctx) {
      const cmdIdx = args.indexOf(command);
      if (cmdIdx !== -1 && args[cmdIdx + 1] && !args[cmdIdx + 1].startsWith("-")) {
        ctx = args[cmdIdx + 1];
      }
    }
    const cleanContext = (ctx ? await readInput(ctx) : "").trim();
    if (!cleanContext) {
      console.error("Error: Context/step description must be provided via argument or stdin.");
      return 2;
    }

    const targetProviderIdx = args.findIndex((a) => a === "--target-provider" || a === "--provider");
    const targetProvider = targetProviderIdx !== -1 ? args[targetProviderIdx + 1] : "openai";

    const modelIdx = args.findIndex((a) => a === "--model" || a === "-m");
    const targetModel = modelIdx !== -1 ? args[modelIdx + 1] : undefined;

    const tokensIdx = args.findIndex((a) => a === "--session-context-tokens" || a === "--tokens");
    const sessionContextTokens = tokensIdx !== -1 ? parseInt(args[tokensIdx + 1], 10) || 0 : 0;

    const effIdx = args.findIndex((a) => a === "--supported-efforts");
    const supportedEfforts = effIdx !== -1 && args[effIdx + 1]
      ? args[effIdx + 1].split(",").map((s) => s.trim().toLowerCase()).filter(Boolean)
      : undefined;

    const leaseIdx = args.findIndex((a) => a === "--max-lease-steps");
    const maxLeaseSteps = leaseIdx !== -1 ? parseInt(args[leaseIdx + 1], 10) || 10 : 10;

    const res = await modulateReasoningEffort(cleanContext, {
      provider: targetProvider,
      model: targetModel,
      sessionContextTokens,
      supportedEfforts,
      maxLeaseSteps,
      client,
    });

    if (isJson) {
      console.log(
        JSON.stringify(
          {
            effort: res.effort,
            confidence: res.confidence,
            complexity_score: res.complexityScore,
            complexityScore: res.complexityScore,
            rationale: res.rationale,
            provider: res.provider,
            provider_params: res.providerParams,
            providerParams: res.providerParams,
            is_reasoning_supported: res.isReasoningSupported,
            isReasoningSupported: res.isReasoningSupported,
            cache_safe_recommendation: res.cacheSafeRecommendation,
            cacheSafeRecommendation: res.cacheSafeRecommendation,
            lease_steps: res.leaseSteps,
            leaseSteps: res.leaseSteps,
            is_mock: res.isMock,
            isMock: res.isMock,
          },
          null,
          2
        )
      );
    } else {
      console.log("\n--- JEV REASONING EFFORT VERDICT (TS) ---");
      console.log(`Effort:            ${res.effort.toUpperCase()}`);
      console.log(`Confidence:        ${(res.confidence * 100).toFixed(1)}%`);
      console.log(`Complexity Score:  ${res.complexityScore.toFixed(1)} / 4.0`);
      console.log(`Lease Steps:       ${res.leaseSteps}`);
      console.log(`Provider:          ${res.provider}`);
      console.log(`Supported:         ${res.isReasoningSupported ? "YES" : "NO (Direct model)"}`);
      console.log(`Rationale:         ${res.rationale}`);
      console.log(`Provider Params:   ${JSON.stringify(res.providerParams)}`);
      if (res.cacheSafeRecommendation) {
        console.log(`Cache Advisory:    ${res.cacheSafeRecommendation}`);
      }
      if (res.isMock) console.log("Mode:              [SIMULATION/MOCK]");
      console.log("-----------------------------------------\n");
    }
    return 0;
  }

  if (command === "nudge-gate" || command === "nudge") {
    const tIdx = args.findIndex((a) => a === "--transcript" || a === "-t");
    let tVal = tIdx !== -1 ? args[tIdx + 1] : undefined;
    if (!tVal) {
      const cmdIdx = args.indexOf(command);
      if (cmdIdx !== -1 && args[cmdIdx + 1] && !args[cmdIdx + 1].startsWith("-")) {
        tVal = args[cmdIdx + 1];
      }
    }
    const cleanTranscript = (tVal ? await readInput(tVal, true) : await readInput(undefined, true)).trim();
    if (!cleanTranscript) {
      console.error("Error: No transcript tail provided. Pass --transcript <text_or_path>, positional arg, or pipe via stdin.");
      return 2;
    }

    const prevIdx = args.findIndex((a) => a === "--previous-nudge" || a === "-P");
    const previousNudgeSummary = prevIdx !== -1 ? (await readInput(args[prevIdx + 1], false)).trim() : "";

    const threshIdx = args.findIndex((a) => a === "--threshold");
    const threshold = threshIdx !== -1 ? parseFloat(args[threshIdx + 1]) || 0.5 : 0.5;

    const res = await shouldNudgeContinuation(cleanTranscript, {
      previousNudgeSummary,
      threshold,
      client,
    });

    if (isJson) {
      console.log(
        JSON.stringify(
          {
            should_nudge: res.shouldNudge,
            shouldNudge: res.shouldNudge,
            nudge_probability: res.nudgeProbability,
            nudgeProbability: res.nudgeProbability,
            waiting_probability: res.waitingProbability,
            waitingProbability: res.waitingProbability,
            progress_probability: res.progressProbability,
            progressProbability: res.progressProbability,
            workflow_phase: res.workflowPhase,
            workflowPhase: res.workflowPhase,
            suggested_nudge_prompt: res.suggestedNudgePrompt,
            suggestedNudgePrompt: res.suggestedNudgePrompt,
            rationale: res.rationale,
            is_mock: res.isMock,
            isMock: res.isMock,
          },
          null,
          2
        )
      );
    } else {
      console.log("\n=== JEV CONTINUATION NUDGE GATE (TS) ===");
      console.log(`Should Nudge:      ${res.shouldNudge ? "YES (Inject Continuation)" : "NO (Stop & Yield to User)"}`);
      console.log(`Workflow Phase:    ${res.workflowPhase.toUpperCase()}`);
      console.log(`Nudge Prob:        ${(res.nudgeProbability * 100).toFixed(1)}%`);
      console.log(`Waiting Prob:      ${(res.waitingProbability * 100).toFixed(1)}%`);
      console.log(`Progress Prob:     ${(res.progressProbability * 100).toFixed(1)}%`);
      console.log(`Rationale:         ${res.rationale}`);
      if (res.suggestedNudgePrompt) {
        console.log(`Suggested Prompt:  ${res.suggestedNudgePrompt}`);
      }
      if (res.isMock) console.log("Engine Mode:       [SIMULATION / MOCK]");
      console.log("========================================\n");
    }
    return res.shouldNudge ? 0 : 1;
  }

  console.error(`Unknown command: ${command}`);
  return 2;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  runCli().then((code) => process.exit(code));
}
