/**
 * Foreman integration surface (thruwire/foreman) — TypeScript mirror of
 * `src/jev_harness/integrations/foreman.py`.
 *
 * Capability matrix (declared, tested, never accidental):
 *   - category, severityScore, confidence, skipLlm, actionRecommendation, assertionSlice
 *     -> Python, TypeScript, Rust
 *   - recovery -> Python only; this runtime always emits `recovery: null`
 *
 * The fingerprint algorithm is runtime-local (`node:crypto` here); only the equality verdict is
 * contractual, never a hex value. `repoRoot` exists for signature parity with the Python adapter
 * and has no effect here (there is no recovery object to scope).
 *
 * Verified against `thruwire/foreman` @ `main` (v0.3.0) on 2026-09-23; re-verify by 2026-10-23.
 */
import { createHash } from "node:crypto";
import { JevClient } from "./client.js";
import { triageTestFailure } from "./gates.js";

export const FOREMAN_SCHEMA_VERSION = 1;
export const ASSERTION_SLICE_MAX_CHARS = 500;
export const DEFAULT_WINDOW = 5;
export const STAGNANT_EVIDENCE = "STAGNANT_EVIDENCE";

export const FOREMAN_PRESET_FILENAME = "quality.jev-triage.toml";
export const FOREMAN_COMPANION_FILENAME = "quality_jev_triage.py";
export const FOREMAN_README_FILENAME = "README.md";
export const FOREMAN_DEFAULT_OUT_DIR = "foreman-responsibilities";

/** Canonical preset, byte-identical across the three runtimes (locked by the shared fixture). */
export const FOREMAN_RESPONSIBILITY_TOML: string = "# quality.jev-triage.toml — jev-harness -> Foreman integration preset.\n# Verified against thruwire/foreman v0.3.0 on 2026-09-23; re-verify by 2026-10-23.\n#\n# SHIP THE PAIR TOGETHER: this file only *configures* a responsibility implementation that must\n# already be installed in the Foreman installation (quality_jev_triage.py, class\n# JevTriageResponsibility). Foreman fails at startup when either half is missing — both exit 2:\n#   * class installed without this central TOML:\n#       ResponsibilityConfigError: installed responsibility has no central configuration: quality.jev-triage\n#   * this TOML without the class:\n#       ResponsibilityConfigError: configuration has no installed responsibility implementation: quality.jev-triage\n#\n# Activate:  foreman run --repo <repo> --job \"<job>\" --responsibilities-dir <this directory>\n#            (or export FOREMAN_RESPONSIBILITIES_DIR=<this directory>)\n# Never place this file inside a managed repository's .foreman/ directory (that is run state).\n\nenabled = true\nalways = false\nrouting_instructions = \"\"\"\nDoes this job involve running automated tests, compilers, or test-suite verification where a deterministic failure classification or stagnation signal would change the next supervisory action?\n\"\"\"\nrouting_threshold = 0.50\n\n[checks.deterministic_recovery_available]\ninstructions = \"\"\"\nDoes the latest worker or verifier output show an environment-classified failure (missing dependency, unusable environment) for which a deterministic recovery exists that the next worker turn could apply without further semantic analysis?\n\"\"\"\nmin_threshold = 0.70\n\n[checks.assertion_failure_critical]\ninstructions = \"\"\"\nDoes the latest test evidence indicate a genuine logic regression (assertion or business-logic failure) rather than an environment or configuration problem? A high probability vetoes proposing a deterministic-recovery retry.\n\"\"\"\nmin_threshold = 0.75\n\n[settings]\ndiff_timeout_seconds = 5\n";
/** Operator README, byte-identical across the three runtimes. */
export const FOREMAN_OPERATOR_README: string = "# jev-harness -> Foreman operator bundle\n\nGenerated by `jev-harness export foreman`. The three files must be installed **together** in the\nForeman installation - never inside a managed repository's `.foreman/` directory (that is run state):\n\n1. `quality.jev-triage.toml` - the central responsibility configuration (routing + checks + settings).\n2. `quality_jev_triage.py`   - the companion responsibility class (`JevTriageResponsibility`).\n3. `README.md`               - this file.\n\n## Why the pair matters (verified against thruwire/foreman v0.3.0 on 2026-09-23)\n\nA TOML only *configures* a responsibility implementation that must already be **installed** in the\nForeman environment. Foreman exits with code 2 when either half is missing:\n\n- class installed without the central TOML:\n  `ResponsibilityConfigError: installed responsibility has no central configuration: quality.jev-triage`\n- this TOML without the class:\n  `ResponsibilityConfigError: configuration has no installed responsibility implementation: quality.jev-triage`\n\n## Activation\n\nPath A - patched launcher (works today): make the class importable in the Foreman environment and\npass it explicitly, e.g.\n\n    responsibilities = configured_registry(config, config_dir=\"<this directory>\",\n                                           additional=[JevTriageResponsibility()])\n\nor register the class in Foreman's `builtin_registry`, then run:\n\n    foreman run --repo <repo> --job \"<job>\" --responsibilities-dir <this directory>\n\n(`FOREMAN_RESPONSIBILITIES_DIR=<this directory>` works as an environment override.)\n\nPath B - upstream registration: the integration PR adds a registration path so stock\n`foreman run` loads the class without a patch (change `foreman-integration`, design Decision 5).\n\n## What the class does\n\n- Reads the latest worker output and a bounded `git diff` (timeout `diff_timeout_seconds`) once per\n  assessment, keyed by `(run_id, iteration)`; re-evaluating an assessment never changes the verdict.\n- Proposes `RETRY_WORKER` only when its own Jev checks clear their thresholds and the evidence\n  window holds `window` assessments: a deterministic environment recovery, or a stagnation verdict\n  (output **and** diff unchanged across the window). A genuine logic regression\n  (`assertion_failure_critical`) vetoes the environment-recovery retry; a provably stagnant worker\n  is retried regardless.\n- Its `reason` is audit evidence (visible in `foreman inspect`); Foreman builds the worker steering\n  text from check probabilities, so the reason does not instruct the worker.\n- It never touches the network by default and never raises into the factory loop.\n\n## Requirements\n\n- `pip install jev-harness` inside the Foreman environment.\n- Python 3.9+ (Foreman itself requires 3.11+).\n\nRe-verify the upstream facts after 2026-10-23.\n";
/** Companion responsibility class source, byte-identical across the three runtimes. */
export const FOREMAN_COMPANION_CLASS_SOURCE: string = "\"\"\"\nForeman responsibility: `quality.jev-triage` (reference implementation shipped with jev-harness).\n\nThis file is exported verbatim by `jev-harness export foreman` into an operator directory and is\nloaded by a Foreman installation through `configured_registry(..., additional=[...])` (or an\nupstream registration). It pairs with `quality.jev-triage.toml`: the TOML only *configures* an\ninstalled class, and Foreman fails at startup when either half is missing.\n\nDesign constraints (change `foreman-integration`, §Decision 6):\n    - deterministic given `(state, result)`; the evidence window is keyed by `(run_id, iteration)`\n      and never double-counts an assessment;\n    - proposes only Foreman's sealed directives, with the `reason` as audit evidence (Foreman\n      builds the worker steering text from check probabilities, never from a directive reason);\n    - the diff reader is injected, bounded and fail-open: a timeout or a missing `git` yields\n      `diff = None`, the breaker declines and the class abstains — it never stalls the event loop\n      beyond `diff_timeout_seconds` plus the child teardown;\n    - no network by default (the triage uses the offline engine); it never raises into the\n      factory loop (fail-open to \"no proposal\").\n\n`foreman` is imported lazily and optionally: inside a real Foreman installation the genuine\n`Directive`/`InterventionType` are used; without it the module still imports and behaves (the\njev-harness test suite exercises this path without installing Foreman).\n\"\"\"\nfrom __future__ import annotations\n\nimport subprocess\nfrom dataclasses import dataclass\nfrom typing import Any, Dict, Iterable, Optional, Sequence, Tuple\n\nfrom jev_harness.integrations.foreman import ForemanCircuitBreaker, ForemanTriageObserver\n\ntry:  # pragma: no cover - the real path runs inside a Foreman installation\n    from foreman.models import Directive, InterventionType  # type: ignore\nexcept ImportError:  # pragma: no cover - stdlib-only fallbacks for jev-harness's own suite\n\n    class InterventionType:  # type: ignore[no-redef]\n        CONTINUE = \"CONTINUE\"\n        RETRY_WORKER = \"RETRY_WORKER\"\n\n    @dataclass\n    class Directive:  # type: ignore[no-redef]\n        action: Any\n        reason: str\n        assessment_iteration: int\n        responsibility_id: str\n        priority: int\n        confidence: Optional[float] = None\n\n\nRESPONSIBILITY_ID = \"quality.jev-triage\"\nRETRY_PRIORITY = 700  # below the safety-critical runtime directives (iteration limit is 950)\nDEFAULT_DIFF_TIMEOUT_SECONDS = 5\nDEFAULT_WINDOW = 5\nDIFF_LIMIT_CHARS = 20_000  # mirrors ObservationBuilder's diff bound\nENVIRONMENT_CATEGORIES = (\"env_missing\", \"flaky_transient\")\n_ALLOWED_SETTINGS = (\"diff_timeout_seconds\", \"window\")\n\n\n@dataclass\nclass _Check:\n    \"\"\"Duck-typed stand-in for `foreman.responsibilities.Check` (same attribute surface).\"\"\"\n\n    responsibility_id: str\n    check_id: str\n    instructions: str = \"\"\n    min_threshold: Optional[float] = None\n\n    @property\n    def key(self) -> str:\n        return f\"{self.responsibility_id}__{self.check_id}\"\n\n\n@dataclass\nclass _Route:\n    \"\"\"Duck-typed stand-in for `foreman.responsibilities.ResponsibilityRoute`.\"\"\"\n\n    always: bool = False\n    instructions: Optional[str] = None\n    threshold: float = 0.5\n\n\ndef _default_diff_runner(repository: str, timeout_seconds: float) -> Optional[str]:\n    \"\"\"Bounded `git diff` read. Any failure (timeout, missing git, non-repo) yields `None`.\"\"\"\n    try:\n        completed = subprocess.run(\n            [\"git\", \"-C\", str(repository), \"diff\", \"--no-ext-diff\"],\n            capture_output=True,\n            text=True,\n            errors=\"replace\",\n            timeout=timeout_seconds,\n        )\n    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):\n        return None\n    if completed.returncode != 0:\n        return None\n    return completed.stdout[-DIFF_LIMIT_CHARS:]\n\n\nclass JevTriageResponsibility:\n    \"\"\"Deterministic worker-health and recovery evidence for Foreman's policy arbiter.\"\"\"\n\n    id = RESPONSIBILITY_ID\n\n    def __init__(\n        self,\n        *,\n        checks: Sequence[Any] = (),\n        diff_runner: Any = None,\n        diff_timeout_seconds: float = DEFAULT_DIFF_TIMEOUT_SECONDS,\n        window: int = DEFAULT_WINDOW,\n    ) -> None:\n        self._checks = tuple(checks)\n        self._diff_runner = diff_runner or _default_diff_runner\n        self._diff_timeout_seconds = float(diff_timeout_seconds)\n        self._window_size = max(2, int(window))\n        self._window: Dict[Tuple[str, int], Dict[str, Any]] = {}\n\n    # -- Foreman `Responsibility` protocol (duck-typed; no foreman import needed) -----------\n\n    def configured(self, settings: Dict[str, Any]) -> \"JevTriageResponsibility\":\n        unknown = sorted(set(settings) - set(_ALLOWED_SETTINGS))\n        if unknown:\n            raise ValueError(f\"unknown settings for {self.id}: {', '.join(unknown)}\")\n        window = settings.get(\"window\", self._window_size)\n        try:\n            window_int = max(2, int(window))\n        except (TypeError, ValueError) as error:\n            raise ValueError(f\"invalid window for {self.id}: {window!r}\") from error\n        timeout = settings.get(\"diff_timeout_seconds\", self._diff_timeout_seconds)\n        try:\n            timeout_float = float(timeout)\n        except (TypeError, ValueError) as error:\n            raise ValueError(f\"invalid diff_timeout_seconds for {self.id}: {timeout!r}\") from error\n        if timeout_float <= 0:\n            raise ValueError(f\"diff_timeout_seconds must be positive for {self.id}\")\n        return JevTriageResponsibility(\n            checks=self._checks,\n            diff_runner=self._diff_runner,\n            diff_timeout_seconds=timeout_float,\n            window=window_int,\n        )\n\n    def configured_checks(self, checks: Iterable[Any]) -> \"JevTriageResponsibility\":\n        return JevTriageResponsibility(\n            checks=tuple(checks),\n            diff_runner=self._diff_runner,\n            diff_timeout_seconds=self._diff_timeout_seconds,\n            window=self._window_size,\n        )\n\n    def route(self) -> Any:\n        return _Route(\n            always=False,\n            instructions=(\n                \"Does this job involve running automated tests, compilers, or test-suite \"\n                \"verification where a deterministic failure classification or stagnation signal \"\n                \"would change the next supervisory action?\"\n            ),\n            threshold=0.5,\n        )\n\n    def checks(self) -> Tuple[Any, ...]:\n        return self._checks\n\n    def directives(self, state: Any, result: Any) -> Sequence[Any]:\n        try:\n            return self._directives(state, result)\n        except Exception:  # fail-open: a broken proposal must never break the factory loop\n            return []\n\n    # -- internals --------------------------------------------------------------------------\n\n    def _check_clears(self, result: Any, check_id: str) -> bool:\n        \"\"\"True when the named check's probability clears its own `min_threshold`.\"\"\"\n        grouped = getattr(result, \"checks\", None) or {}\n        probability = (grouped.get(self.id) or {}).get(check_id)\n        if not isinstance(probability, (int, float)) or isinstance(probability, bool):\n            return False\n        for check in self._checks:\n            if getattr(check, \"responsibility_id\", None) != self.id:\n                continue\n            if getattr(check, \"check_id\", None) != check_id:\n                continue\n            threshold = getattr(check, \"min_threshold\", None)\n            return threshold is None or float(probability) >= float(threshold)\n        return False\n\n    def _score(self, result: Any, check_id: str) -> Optional[float]:\n        grouped = getattr(result, \"checks\", None) or {}\n        probability = (grouped.get(self.id) or {}).get(check_id)\n        if isinstance(probability, (int, float)) and not isinstance(probability, bool):\n            return float(probability)\n        return None\n\n    def _record_evidence(self, state: Any) -> Optional[str]:\n        \"\"\"Adds one `(run_id, iteration)`-keyed snapshot (insert-once) and returns the output.\"\"\"\n        workers = list(getattr(state, \"workers\", None) or [])\n        if not workers:\n            return None\n        latest = workers[-1]\n        output = f\"{getattr(latest, 'stdout', '') or ''}\\n{getattr(latest, 'stderr', '') or ''}\".strip()\n        if not output:\n            return None\n        key = (str(getattr(state, \"run_id\", \"\")), int(getattr(state, \"iteration\", 0)))\n        if key not in self._window:\n            diff = self._diff_runner(str(getattr(state, \"repository\", \"\") or \"\"), self._diff_timeout_seconds)\n            self._window[key] = {\"output\": output, \"diff\": diff if isinstance(diff, str) else None}\n            if len(self._window) > self._window_size:\n                oldest = next(iter(self._window))\n                self._window.pop(oldest, None)\n        return output\n\n    def _directives(self, state: Any, result: Any) -> Sequence[Any]:\n        output = self._record_evidence(state)\n        if output is None:\n            return []\n        if not self._check_clears(result, \"deterministic_recovery_available\"):\n            return []\n\n        iteration = int(getattr(state, \"iteration\", 0) or 0)\n        samples = list(self._window.values())\n        verdict = ForemanCircuitBreaker.evaluate_worker_health(samples, window=self._window_size)\n        # No proposal until the evidence window is complete: the spec's \"no evidence, no\n        # proposal\" scenario and the restart-safety property both require it, and a single\n        # assessment cannot distinguish a fixed transient error from a live one.\n        if verdict[\"evidence\"][\"insufficient_history\"]:\n            return []\n        if verdict[\"should_abort\"]:\n            return [\n                Directive(\n                    action=InterventionType.RETRY_WORKER,\n                    reason=(\n                        f\"{verdict['reason']}: worker output and repository diff were unchanged \"\n                        f\"across {verdict['evidence']['samples']} assessments\"\n                    ),\n                    assessment_iteration=max(1, iteration),\n                    responsibility_id=self.id,\n                    priority=RETRY_PRIORITY,\n                    confidence=self._score(result, \"deterministic_recovery_available\"),\n                )\n            ]\n\n        # A genuine logic regression vetoes a \"deterministic recovery\" retry: retrying would be a\n        # false claim of determinism, so the semantic path keeps that decision.\n        if self._check_clears(result, \"assertion_failure_critical\"):\n            return []\n\n        records = ForemanTriageObserver.extract_test_results(\n            output, repo_root=getattr(state, \"repository\", None)\n        )\n        if not records:\n            return []\n        record = records[0]\n        if not record[\"skip_llm\"] or record[\"category\"] not in ENVIRONMENT_CATEGORIES:\n            return []\n        recovery = record.get(\"recovery\") or {}\n        detail = recovery.get(\"rationale\") or record[\"action_recommendation\"]\n        return [\n            Directive(\n                action=InterventionType.RETRY_WORKER,\n                reason=(\n                    f\"deterministic recovery available ({record['category']}): {detail}\"\n                ),\n                assessment_iteration=max(1, iteration),\n                responsibility_id=self.id,\n                priority=RETRY_PRIORITY,\n                confidence=self._score(result, \"deterministic_recovery_available\"),\n            )\n        ]\n";

export interface ForemanTriageRecord {
  category: string;
  severityScore: number;
  confidence: number;
  skipLlm: boolean;
  actionRecommendation: string;
  assertionSlice: string;
  /** Python-only (capability matrix): always `null` in this runtime. */
  recovery: null;
  isMock: boolean;
  degradedReason: string;
  foremanSchemaVersion: number;
}

export interface ForemanSnapshot {
  output: string;
  diff: string | null;
}

export interface ForemanHealthVerdict {
  shouldAbort: boolean;
  reason: string;
  evidence: {
    insufficientHistory: boolean;
    completeSignals: boolean;
    samples: number;
    window: number;
    stagnantOutput: boolean;
    stagnantDiff: boolean;
  };
}

// Same regex family as `src/jev_harness/perception.py::_ASSERTION_LINE`.
const ASSERTION_LINE =
  /(?:assertionerror|assertion failed|assert\s|assert_eq!|expected:.*received:|^\s*(?:FAILED|FAIL|not ok|E\s{2,})\b|error(?:\[[A-Z]+\d+\]| TS\d+| CS\d+)?:|panic:|panicked at|segmentation fault|sigsegv|core dumped|falha de asserção|fallo de aserción|assertionerror)/im;

/** The single most informative line of a failure log, or null when there is no clear one. */
export function findAssertionLine(text: string): string | null {
  if (!text) return null;
  for (const line of text.split(/\r?\n/)) {
    if (ASSERTION_LINE.test(line)) return line.trim();
  }
  return null;
}

const VOLATILE_PATTERNS: RegExp[] = [
  /\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?\b/g,
  /\b\d+(?:\.\d+)?\s?(?:ms|s|sec|secs|seconds|min|mins|h|hours)\b/g,
  /(?::\d+){1,2}(?=[\s:)\]}]|$)/g,
  /\bline \d+\b/gi,
  /(?:\/tmp|\/var\/folders\/)[^\s]*/g,
  /\b[0-9a-f]{7,64}\b/gi,
];

export function normalizeOutput(text: string): string {
  let normalized = text ?? "";
  for (const pattern of VOLATILE_PATTERNS) normalized = normalized.replace(pattern, "<v>");
  return normalized.replace(/\s+/g, " ").trim();
}

function fingerprint(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

/** Deterministic triage records for `FactoryObservation.test_results` (one record per log). */
export async function extractTestResults(
  stdout: string,
  stderr = "",
  repoRoot?: string,
  client?: JevClient
): Promise<ForemanTriageRecord[]> {
  void repoRoot; // signature parity only: recovery is Python-only (capability matrix)
  const output = `${stdout}\n${stderr}`.trim();
  if (!output) return [];
  const result = await triageTestFailure(output, client ?? new JevClient({ forceMock: true }));
  if (result.category === "no_failure") return [];
  return [
    {
      category: result.category,
      severityScore: result.severityScore,
      confidence: result.confidence,
      skipLlm: result.skipLlm,
      actionRecommendation: result.actionRecommendation,
      assertionSlice: (findAssertionLine(output) ?? "").slice(0, ASSERTION_SLICE_MAX_CHARS),
      recovery: null,
      isMock: result.isMock,
      degradedReason: result.degradedReason,
      foremanSchemaVersion: FOREMAN_SCHEMA_VERSION,
    },
  ];
}

/**
 * Conservative stagnation evidence: abort only when the output fingerprint AND the diff
 * fingerprint are unchanged across the whole window. No diff in the window -> decline.
 */
export function evaluateWorkerHealth(
  snapshots: ForemanSnapshot[],
  window: number = DEFAULT_WINDOW
): ForemanHealthVerdict {
  const samples = snapshots ?? [];
  const effectiveWindow = Math.max(2, Math.trunc(window));

  if (samples.length < effectiveWindow) {
    return {
      shouldAbort: false,
      reason: "",
      evidence: {
        insufficientHistory: true,
        completeSignals: false,
        samples: samples.length,
        window: effectiveWindow,
        stagnantOutput: false,
        stagnantDiff: false,
      },
    };
  }

  const recent = samples.slice(-effectiveWindow);
  const completeSignals = recent.every((sample) => typeof sample.diff === "string");

  const outputFingerprints = new Set(recent.map((sample) => fingerprint(normalizeOutput(sample.output ?? ""))));
  const stagnantOutput = outputFingerprints.size === 1;

  let stagnantDiff = false;
  if (completeSignals) {
    stagnantDiff = new Set(recent.map((sample) => fingerprint(String(sample.diff)))).size === 1;
  }

  const shouldAbort = stagnantOutput && stagnantDiff;
  return {
    shouldAbort,
    reason: shouldAbort ? STAGNANT_EVIDENCE : "",
    evidence: {
      insufficientHistory: false,
      completeSignals,
      samples: recent.length,
      window: effectiveWindow,
      stagnantOutput,
      stagnantDiff,
    },
  };
}
