//! Foreman integration surface (thruwire/foreman) — Rust mirror of the Python/TypeScript adapters.
//!
//! Capability matrix (declared, tested, never accidental):
//!   - category, severity_score, confidence, skip_llm, action_recommendation, assertion_slice
//!     -> Python, TypeScript, Rust
//!   - recovery -> Python only; this runtime always emits `recovery: None`
//!
//! The fingerprint algorithm is runtime-local: this runtime compares the normalized strings
//! directly, because only the equality verdict is contractual and never a digest value.
//! `repo_root` exists for signature parity with the Python adapter and has no effect here.
//!
//! Verified against `thruwire/foreman` @ `main` (v0.3.0) on 2026-09-23; re-verify by 2026-10-23.

use crate::client::JevClient;
use crate::gates::triage_test_failure;
use crate::types::JevError;
use regex::Regex;
use std::collections::HashSet;
use std::sync::OnceLock;

pub const FOREMAN_SCHEMA_VERSION: u32 = 1;
pub const ASSERTION_SLICE_MAX_CHARS: usize = 500;
pub const DEFAULT_WINDOW: usize = 5;
pub const STAGNANT_EVIDENCE: &str = "STAGNANT_EVIDENCE";

pub const FOREMAN_PRESET_FILENAME: &str = "quality.jev-triage.toml";
pub const FOREMAN_COMPANION_FILENAME: &str = "quality_jev_triage.py";
pub const FOREMAN_README_FILENAME: &str = "README.md";
pub const FOREMAN_DEFAULT_OUT_DIR: &str = "foreman-responsibilities";

/// Canonical preset, byte-identical across the three runtimes (locked by the shared fixture).
pub const FOREMAN_RESPONSIBILITY_TOML: &str = r#"# quality.jev-triage.toml — jev-harness -> Foreman integration preset.
# Verified against thruwire/foreman v0.3.0 on 2026-09-23; re-verify by 2026-10-23.
#
# SHIP THE PAIR TOGETHER: this file only *configures* a responsibility implementation that must
# already be installed in the Foreman installation (quality_jev_triage.py, class
# JevTriageResponsibility). Foreman fails at startup when either half is missing — both exit 2:
#   * class installed without this central TOML:
#       ResponsibilityConfigError: installed responsibility has no central configuration: quality.jev-triage
#   * this TOML without the class:
#       ResponsibilityConfigError: configuration has no installed responsibility implementation: quality.jev-triage
#
# Activate:  foreman run --repo <repo> --job "<job>" --responsibilities-dir <this directory>
#            (or export FOREMAN_RESPONSIBILITIES_DIR=<this directory>)
# Never place this file inside a managed repository's .foreman/ directory (that is run state).

enabled = true
always = false
routing_instructions = """
Does this job involve running automated tests, compilers, or test-suite verification where a deterministic failure classification or stagnation signal would change the next supervisory action?
"""
routing_threshold = 0.50

[checks.deterministic_recovery_available]
instructions = """
Does the latest worker or verifier output show an environment-classified failure (missing dependency, unusable environment) for which a deterministic recovery exists that the next worker turn could apply without further semantic analysis?
"""
min_threshold = 0.70

[checks.assertion_failure_critical]
instructions = """
Does the latest test evidence indicate a genuine logic regression (assertion or business-logic failure) rather than an environment or configuration problem? A high probability vetoes proposing a deterministic-recovery retry.
"""
min_threshold = 0.75

[settings]
diff_timeout_seconds = 5
"#;
/// Operator README, byte-identical across the three runtimes.
pub const FOREMAN_OPERATOR_README: &str = r#"# jev-harness -> Foreman operator bundle

Generated by `jev-harness export foreman`. The three files must be installed **together** in the
Foreman installation - never inside a managed repository's `.foreman/` directory (that is run state):

1. `quality.jev-triage.toml` - the central responsibility configuration (routing + checks + settings).
2. `quality_jev_triage.py`   - the companion responsibility class (`JevTriageResponsibility`).
3. `README.md`               - this file.

## Why the pair matters (verified against thruwire/foreman v0.3.0 on 2026-09-23)

A TOML only *configures* a responsibility implementation that must already be **installed** in the
Foreman environment. Foreman exits with code 2 when either half is missing:

- class installed without the central TOML:
  `ResponsibilityConfigError: installed responsibility has no central configuration: quality.jev-triage`
- this TOML without the class:
  `ResponsibilityConfigError: configuration has no installed responsibility implementation: quality.jev-triage`

## Activation

Path A - patched launcher (works today): make the class importable in the Foreman environment and
pass it explicitly, e.g.

    responsibilities = configured_registry(config, config_dir="<this directory>",
                                           additional=[JevTriageResponsibility()])

or register the class in Foreman's `builtin_registry`, then run:

    foreman run --repo <repo> --job "<job>" --responsibilities-dir <this directory>

(`FOREMAN_RESPONSIBILITIES_DIR=<this directory>` works as an environment override.)

Path B - upstream registration: the integration PR adds a registration path so stock
`foreman run` loads the class without a patch (change `foreman-integration`, design Decision 5).

## What the class does

- Reads the latest worker output and a bounded `git diff` (timeout `diff_timeout_seconds`) once per
  assessment, keyed by `(run_id, iteration)`; re-evaluating an assessment never changes the verdict.
- Proposes `RETRY_WORKER` only when its own Jev checks clear their thresholds and the evidence
  window holds `window` assessments: a deterministic environment recovery, or a stagnation verdict
  (output **and** diff unchanged across the window). A genuine logic regression
  (`assertion_failure_critical`) vetoes the environment-recovery retry; a provably stagnant worker
  is retried regardless.
- Its `reason` is audit evidence (visible in `foreman inspect`); Foreman builds the worker steering
  text from check probabilities, so the reason does not instruct the worker.
- It never touches the network by default and never raises into the factory loop.

## Requirements

- `pip install jev-harness` inside the Foreman environment.
- Python 3.9+ (Foreman itself requires 3.11+).

Re-verify the upstream facts after 2026-10-23.
"#;
/// Companion responsibility class source, byte-identical across the three runtimes.
pub const FOREMAN_COMPANION_CLASS_SOURCE: &str = r#""""
Foreman responsibility: `quality.jev-triage` (reference implementation shipped with jev-harness).

This file is exported verbatim by `jev-harness export foreman` into an operator directory and is
loaded by a Foreman installation through `configured_registry(..., additional=[...])` (or an
upstream registration). It pairs with `quality.jev-triage.toml`: the TOML only *configures* an
installed class, and Foreman fails at startup when either half is missing.

Design constraints (change `foreman-integration`, §Decision 6):
    - deterministic given `(state, result)`; the evidence window is keyed by `(run_id, iteration)`
      and never double-counts an assessment;
    - proposes only Foreman's sealed directives, with the `reason` as audit evidence (Foreman
      builds the worker steering text from check probabilities, never from a directive reason);
    - the diff reader is injected, bounded and fail-open: a timeout or a missing `git` yields
      `diff = None`, the breaker declines and the class abstains — it never stalls the event loop
      beyond `diff_timeout_seconds` plus the child teardown;
    - no network by default (the triage uses the offline engine); it never raises into the
      factory loop (fail-open to "no proposal").

`foreman` is imported lazily and optionally: inside a real Foreman installation the genuine
`Directive`/`InterventionType` are used; without it the module still imports and behaves (the
jev-harness test suite exercises this path without installing Foreman).
"""
from __future__ import annotations

import subprocess
from dataclasses import dataclass
from typing import Any, Dict, Iterable, Optional, Sequence, Tuple

from jev_harness.integrations.foreman import ForemanCircuitBreaker, ForemanTriageObserver

try:  # pragma: no cover - the real path runs inside a Foreman installation
    from foreman.models import Directive, InterventionType  # type: ignore
except ImportError:  # pragma: no cover - stdlib-only fallbacks for jev-harness's own suite

    class InterventionType:  # type: ignore[no-redef]
        CONTINUE = "CONTINUE"
        RETRY_WORKER = "RETRY_WORKER"

    @dataclass
    class Directive:  # type: ignore[no-redef]
        action: Any
        reason: str
        assessment_iteration: int
        responsibility_id: str
        priority: int
        confidence: Optional[float] = None


RESPONSIBILITY_ID = "quality.jev-triage"
RETRY_PRIORITY = 700  # below the safety-critical runtime directives (iteration limit is 950)
DEFAULT_DIFF_TIMEOUT_SECONDS = 5
DEFAULT_WINDOW = 5
DIFF_LIMIT_CHARS = 20_000  # mirrors ObservationBuilder's diff bound
ENVIRONMENT_CATEGORIES = ("env_missing", "flaky_transient")
_ALLOWED_SETTINGS = ("diff_timeout_seconds", "window")


@dataclass
class _Check:
    """Duck-typed stand-in for `foreman.responsibilities.Check` (same attribute surface)."""

    responsibility_id: str
    check_id: str
    instructions: str = ""
    min_threshold: Optional[float] = None

    @property
    def key(self) -> str:
        return f"{self.responsibility_id}__{self.check_id}"


@dataclass
class _Route:
    """Duck-typed stand-in for `foreman.responsibilities.ResponsibilityRoute`."""

    always: bool = False
    instructions: Optional[str] = None
    threshold: float = 0.5


def _default_diff_runner(repository: str, timeout_seconds: float) -> Optional[str]:
    """Bounded `git diff` read. Any failure (timeout, missing git, non-repo) yields `None`."""
    try:
        completed = subprocess.run(
            ["git", "-C", str(repository), "diff", "--no-ext-diff"],
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout_seconds,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return None
    if completed.returncode != 0:
        return None
    return completed.stdout[-DIFF_LIMIT_CHARS:]


class JevTriageResponsibility:
    """Deterministic worker-health and recovery evidence for Foreman's policy arbiter."""

    id = RESPONSIBILITY_ID

    def __init__(
        self,
        *,
        checks: Sequence[Any] = (),
        diff_runner: Any = None,
        diff_timeout_seconds: float = DEFAULT_DIFF_TIMEOUT_SECONDS,
        window: int = DEFAULT_WINDOW,
    ) -> None:
        self._checks = tuple(checks)
        self._diff_runner = diff_runner or _default_diff_runner
        self._diff_timeout_seconds = float(diff_timeout_seconds)
        self._window_size = max(2, int(window))
        self._window: Dict[Tuple[str, int], Dict[str, Any]] = {}

    # -- Foreman `Responsibility` protocol (duck-typed; no foreman import needed) -----------

    def configured(self, settings: Dict[str, Any]) -> "JevTriageResponsibility":
        unknown = sorted(set(settings) - set(_ALLOWED_SETTINGS))
        if unknown:
            raise ValueError(f"unknown settings for {self.id}: {', '.join(unknown)}")
        window = settings.get("window", self._window_size)
        try:
            window_int = max(2, int(window))
        except (TypeError, ValueError) as error:
            raise ValueError(f"invalid window for {self.id}: {window!r}") from error
        timeout = settings.get("diff_timeout_seconds", self._diff_timeout_seconds)
        try:
            timeout_float = float(timeout)
        except (TypeError, ValueError) as error:
            raise ValueError(f"invalid diff_timeout_seconds for {self.id}: {timeout!r}") from error
        if timeout_float <= 0:
            raise ValueError(f"diff_timeout_seconds must be positive for {self.id}")
        return JevTriageResponsibility(
            checks=self._checks,
            diff_runner=self._diff_runner,
            diff_timeout_seconds=timeout_float,
            window=window_int,
        )

    def configured_checks(self, checks: Iterable[Any]) -> "JevTriageResponsibility":
        return JevTriageResponsibility(
            checks=tuple(checks),
            diff_runner=self._diff_runner,
            diff_timeout_seconds=self._diff_timeout_seconds,
            window=self._window_size,
        )

    def route(self) -> Any:
        return _Route(
            always=False,
            instructions=(
                "Does this job involve running automated tests, compilers, or test-suite "
                "verification where a deterministic failure classification or stagnation signal "
                "would change the next supervisory action?"
            ),
            threshold=0.5,
        )

    def checks(self) -> Tuple[Any, ...]:
        return self._checks

    def directives(self, state: Any, result: Any) -> Sequence[Any]:
        try:
            return self._directives(state, result)
        except Exception:  # fail-open: a broken proposal must never break the factory loop
            return []

    # -- internals --------------------------------------------------------------------------

    def _check_clears(self, result: Any, check_id: str) -> bool:
        """True when the named check's probability clears its own `min_threshold`."""
        grouped = getattr(result, "checks", None) or {}
        probability = (grouped.get(self.id) or {}).get(check_id)
        if not isinstance(probability, (int, float)) or isinstance(probability, bool):
            return False
        for check in self._checks:
            if getattr(check, "responsibility_id", None) != self.id:
                continue
            if getattr(check, "check_id", None) != check_id:
                continue
            threshold = getattr(check, "min_threshold", None)
            return threshold is None or float(probability) >= float(threshold)
        return False

    def _score(self, result: Any, check_id: str) -> Optional[float]:
        grouped = getattr(result, "checks", None) or {}
        probability = (grouped.get(self.id) or {}).get(check_id)
        if isinstance(probability, (int, float)) and not isinstance(probability, bool):
            return float(probability)
        return None

    def _record_evidence(self, state: Any) -> Optional[str]:
        """Adds one `(run_id, iteration)`-keyed snapshot (insert-once) and returns the output."""
        workers = list(getattr(state, "workers", None) or [])
        if not workers:
            return None
        latest = workers[-1]
        output = f"{getattr(latest, 'stdout', '') or ''}\n{getattr(latest, 'stderr', '') or ''}".strip()
        if not output:
            return None
        key = (str(getattr(state, "run_id", "")), int(getattr(state, "iteration", 0)))
        if key not in self._window:
            diff = self._diff_runner(str(getattr(state, "repository", "") or ""), self._diff_timeout_seconds)
            self._window[key] = {"output": output, "diff": diff if isinstance(diff, str) else None}
            if len(self._window) > self._window_size:
                oldest = next(iter(self._window))
                self._window.pop(oldest, None)
        return output

    def _directives(self, state: Any, result: Any) -> Sequence[Any]:
        output = self._record_evidence(state)
        if output is None:
            return []
        if not self._check_clears(result, "deterministic_recovery_available"):
            return []

        iteration = int(getattr(state, "iteration", 0) or 0)
        samples = list(self._window.values())
        verdict = ForemanCircuitBreaker.evaluate_worker_health(samples, window=self._window_size)
        # No proposal until the evidence window is complete: the spec's "no evidence, no
        # proposal" scenario and the restart-safety property both require it, and a single
        # assessment cannot distinguish a fixed transient error from a live one.
        if verdict["evidence"]["insufficient_history"]:
            return []
        if verdict["should_abort"]:
            return [
                Directive(
                    action=InterventionType.RETRY_WORKER,
                    reason=(
                        f"{verdict['reason']}: worker output and repository diff were unchanged "
                        f"across {verdict['evidence']['samples']} assessments"
                    ),
                    assessment_iteration=max(1, iteration),
                    responsibility_id=self.id,
                    priority=RETRY_PRIORITY,
                    confidence=self._score(result, "deterministic_recovery_available"),
                )
            ]

        # A genuine logic regression vetoes a "deterministic recovery" retry: retrying would be a
        # false claim of determinism, so the semantic path keeps that decision.
        if self._check_clears(result, "assertion_failure_critical"):
            return []

        records = ForemanTriageObserver.extract_test_results(
            output, repo_root=getattr(state, "repository", None)
        )
        if not records:
            return []
        record = records[0]
        if not record["skip_llm"] or record["category"] not in ENVIRONMENT_CATEGORIES:
            return []
        recovery = record.get("recovery") or {}
        detail = recovery.get("rationale") or record["action_recommendation"]
        return [
            Directive(
                action=InterventionType.RETRY_WORKER,
                reason=(
                    f"deterministic recovery available ({record['category']}): {detail}"
                ),
                assessment_iteration=max(1, iteration),
                responsibility_id=self.id,
                priority=RETRY_PRIORITY,
                confidence=self._score(result, "deterministic_recovery_available"),
            )
        ]
"#;

/// One structured failure record for `FactoryObservation.test_results`.
#[derive(Debug, Clone, PartialEq)]
pub struct ForemanTriageRecord {
    pub category: String,
    pub severity_score: f64,
    pub confidence: f64,
    pub skip_llm: bool,
    pub action_recommendation: String,
    pub assertion_slice: String,
    /// Python-only (capability matrix): always `None` in this runtime.
    pub recovery: Option<serde_json::Value>,
    pub is_mock: bool,
    pub degraded_reason: String,
    pub foreman_schema_version: u32,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ForemanSnapshot {
    pub output: String,
    pub diff: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ForemanHealthEvidence {
    pub insufficient_history: bool,
    pub complete_signals: bool,
    pub samples: usize,
    pub window: usize,
    pub stagnant_output: bool,
    pub stagnant_diff: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ForemanHealthVerdict {
    pub should_abort: bool,
    pub reason: String,
    pub evidence: ForemanHealthEvidence,
}

// Same regex family as `src/jev_harness/perception.py::_ASSERTION_LINE`. The `regex` crate has no
// look-around, so the assertion family below uses none.
fn assertion_line_regex() -> &'static Regex {
    static PATTERN: OnceLock<Regex> = OnceLock::new();
    PATTERN.get_or_init(|| {
        Regex::new(
            r"(?i)(?:assertionerror|assertion failed|assert\s|assert_eq!|expected:.*received:|^\s*(?:FAILED|FAIL|not ok|E\s{2,})\b|error(?:\[[A-Z]+\d+\]| TS\d+| CS\d+)?:|panic:|panicked at|segmentation fault|sigsegv|core dumped|falha de asserção|fallo de aserción)",
        )
        .expect("static assertion pattern compiles")
    })
}

/// The single most informative line of a failure log, or `None` when there is no clear one.
pub fn find_assertion_line(text: &str) -> Option<String> {
    if text.is_empty() {
        return None;
    }
    let pattern = assertion_line_regex();
    text.lines()
        .find(|line| pattern.is_match(line))
        .map(|line| line.trim().to_string())
}

// Volatile tokens stripped before comparing output tails. The line-reference pattern consumes the
// following character and re-inserts it through a capture group (no look-around available).
fn volatile_patterns() -> &'static Vec<Regex> {
    static PATTERNS: OnceLock<Vec<Regex>> = OnceLock::new();
    PATTERNS.get_or_init(|| {
        [
            r"\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?\b",
            r"\b\d+(?:\.\d+)?\s?(?:ms|s|sec|secs|seconds|min|mins|h|hours)\b",
            r"(?::\d+){1,2}([\s:)\]}]|$)",
            r"(?i)\bline \d+\b",
            r"(?:/tmp|/var/folders/)[^\s]*",
            r"(?i)\b[0-9a-f]{7,64}\b",
        ]
        .iter()
        .map(|pattern| Regex::new(pattern).expect("static volatile pattern compiles"))
        .collect()
    })
}

fn whitespace_regex() -> &'static Regex {
    static PATTERN: OnceLock<Regex> = OnceLock::new();
    PATTERN.get_or_init(|| Regex::new(r"\s+").expect("static whitespace pattern compiles"))
}

/// Whitespace-collapsed text with volatile tokens replaced (the stagnation comparison unit).
pub fn normalize_output(text: &str) -> String {
    let mut normalized = text.to_string();
    for pattern in volatile_patterns() {
        normalized = pattern.replace_all(&normalized, "<v>$1").into_owned();
    }
    whitespace_regex().replace_all(&normalized, " ").trim().to_string()
}

/// Deterministic triage records for `FactoryObservation.test_results` (one record per log).
pub async fn extract_test_results(
    stdout: &str,
    stderr: &str,
    repo_root: Option<&str>,
    client: Option<&JevClient>,
) -> Result<Vec<ForemanTriageRecord>, JevError> {
    let _ = repo_root; // signature parity only: recovery is Python-only (capability matrix)
    let output = format!("{}\n{}", stdout, stderr);
    let output = output.trim();
    if output.is_empty() {
        return Ok(Vec::new());
    }

    let fallback_client;
    let active_client = match client {
        Some(configured) => configured,
        None => {
            fallback_client = JevClient::with_mock();
            &fallback_client
        }
    };

    let result = triage_test_failure(output, Some(active_client)).await?;
    if result.category == "no_failure" {
        return Ok(Vec::new());
    }

    let assertion_slice = find_assertion_line(output).unwrap_or_default();
    Ok(vec![ForemanTriageRecord {
        category: result.category,
        severity_score: result.severity_score,
        confidence: result.confidence,
        skip_llm: result.skip_llm,
        action_recommendation: result.action_recommendation,
        assertion_slice: assertion_slice.chars().take(ASSERTION_SLICE_MAX_CHARS).collect(),
        recovery: None,
        is_mock: result.is_mock,
        degraded_reason: result.degraded_reason,
        foreman_schema_version: FOREMAN_SCHEMA_VERSION,
    }])
}

/// Conservative stagnation evidence: abort only when the normalized output AND the diff are
/// unchanged across the whole window. No diff in the window -> decline (`complete_signals: false`).
pub fn evaluate_worker_health(snapshots: &[ForemanSnapshot], window: usize) -> ForemanHealthVerdict {
    let effective_window = window.max(2);

    if snapshots.len() < effective_window {
        return ForemanHealthVerdict {
            should_abort: false,
            reason: String::new(),
            evidence: ForemanHealthEvidence {
                insufficient_history: true,
                complete_signals: false,
                samples: snapshots.len(),
                window: effective_window,
                stagnant_output: false,
                stagnant_diff: false,
            },
        };
    }

    let recent = &snapshots[snapshots.len() - effective_window..];
    let complete_signals = recent.iter().all(|snapshot| snapshot.diff.is_some());

    let outputs: HashSet<String> = recent
        .iter()
        .map(|snapshot| normalize_output(&snapshot.output))
        .collect();
    let stagnant_output = outputs.len() == 1;

    let mut stagnant_diff = false;
    if complete_signals {
        let diffs: HashSet<String> = recent
            .iter()
            .map(|snapshot| snapshot.diff.clone().unwrap_or_default())
            .collect();
        stagnant_diff = diffs.len() == 1;
    }

    let should_abort = stagnant_output && stagnant_diff;
    ForemanHealthVerdict {
        should_abort,
        reason: if should_abort {
            STAGNANT_EVIDENCE.to_string()
        } else {
            String::new()
        },
        evidence: ForemanHealthEvidence {
            insufficient_history: false,
            complete_signals,
            samples: recent.len(),
            window: effective_window,
            stagnant_output,
            stagnant_diff,
        },
    }
}
